### PR TITLE
Fix EBS persistence

### LINKED ISSUE #155: Make EBS volume actually persistent

### PR DESCRIPTION
**Pull request by sirrus233**
Resolves #155

### CODE REVIEW

File: infrastructure/lib/infrastructure-stack.ts [hunk 1]
```diff
@@ -104,24 +104,28 @@ export class InfrastructureStack extends cdk.Stack {
...
+            volumeType: ec2.EbsDeviceVolumeType.GP3,
+            removalPolicy: cdk.RemovalPolicy.RETAIN,
+        });
+
+        new ec2.CfnVolumeAttachment(this, "AttachServerStorage", {
+            volumeId: ebsVolume.volumeId,
+            instanceId: instance.instanceId,
+            device: "/dev/sda2",
+        });
+
```
Comment (chelseaSchmidt) [inline infrastructure/lib/infrastructure-stack.ts:126]: What ended up being the difference between these two methods? Here is my blind approval though haha

**Review by chelseaSchmidt — APPROVED** [review]

File: infrastructure/lib/infrastructure-stack.ts (hunk 1 above)
Comment (sirrus233) [reply infrastructure/lib/infrastructure-stack.ts:126]: The difference between explicitly creating a new Volume object via `new ec2.Volume(...)` vs configuring one via parameters in the `Instance` object.

In the former case, a block storage device is created as a separate resource with CDK managing its life-cycle independently of the instance. In the latter, it has no existence of its own, so you get a new volume each time the instance is replaced.

Comment (chelseaSchmidt) [reply infrastructure/lib/infrastructure-stack.ts:126]: Gotcha that makes sense!
